Added dev container #175
StackGuardian/tirith pull request #181
Opened 2024-09-23 04:25 UTC by AkashS0510

Added Dev Conatiner #175

2024-09-23 05:32 UTC, refeed requested changes

2024-09-23 05:32 UTC, refeed commented on README.md
> +# Development Container Setup
I'd move this under the "For developers" section

2024-09-23 05:32 UTC, refeed commented on README.md
> +
There are a lot of formatting changes here, could you please not include it in this commit. We can maybe have a separate issue regarding this (adding a doc linter, but need discussion first)

2024-09-25 13:01 UTC, refeed approved these changes

2024-09-25 13:01 UTC, refeed commented on README.md
> +## Running the Dev Container
Use the h4

2024-09-25 13:01 UTC, refeed commented on README.md
> +## Manual Installation
Use h4

2024-09-25 17:19 UTC, samriddhi99 approved these changes

2024-09-25 17:19 UTC, merged